<?php

////////////////////////////////////////
// ATAQUES ALEATORIOS

if ($tipoCombate == "umbral") { $typeOfSkillToPick = 5; }

srand((float) microtime() * 10000000);

	switch($typeOfSkillToPick) {
		case 3:
			$attack = array (
			"dispara",
			"pega un tiro",
			"fusila",
			"tirotea",
			"intenta alcanzar",
			"apunta a la cabeza"
			);
			break;
		case 4:
			$attack = array (
			"ataca",
			"agrede"
			);
			break;
		case 5:
			$attack = array (
			"lanza una bola de energía",
			"proyecta fuerza espiritual",
			"asalta el espíritu"
			);
			break;
		default:
			$attack = array(
			"agrede", 
			"ataca",
			"golpea",
			"amenaza",
			"prueba a golpear",
			"se aproxima con intenciones hostiles",
			"se tira sobre su enemigo",
			"se abalanza con violencia",
			"descarga su furia"
			);
			break;
	}
	$numberOfQuotes = count($attack);
// Random quote is generated by array_rand and the variable is assigned to it
//The number in the parenthesis = number of quotes you have in total
$atakc = array_rand($attack,$numberOfQuotes);
$atak = $attack[$atakc[1]];

///////////////////////////////////////

////////////////////////////////////////
// FALLOS ALEATORIOS

srand((float) microtime() * 10000000);

	switch($typeOfSkillToPick) {
		case 3:
			$fails = array (
			"falla el tiro",
			"ve frustrado su disparo",
			"tiene muy mala punter&iacute;a",
			"ha tenido un disparo de pena",
			"ve como el proyectil se pierde en la lejan&iacute;a",
			"erra completamente el tiro",
			"no acierta al disparar",
			"falla el disparo"
			);
			break;
		case 4:
			$fails = array (
			"falla",
			"no acierta",
			"golpea el suelo"
			);
			break;
		case 5:
			$fails = array (
			"no hace daño",
			"no es eficaz",
			"ve como su ataque es atenuado por completo"
			);
			break;
		default:
			$fails = array(
			"falla su ataque",
			"falla estrepitosamente",
			"ve frustrada su agresión",
			"tropieza",
			"fracasa en el intento de causar daño",
			"golpea a una pared cercana, arruinando su ataque",
			"observa como su ataque es esquivado grácilmente",
			"pisa un socavón que había por el suelo, fallando el ataque",
			"se resbala con una piel de plátano",
			"no consigue impactar",
			"golpea al aire"
			);
			break;
	}
	$numberOfQuotes = count($fails);
// Random quote is generated by array_rand and the variable is assigned to it
//The number in the parenthesis = number of quotes you have in total
$faisl = array_rand($fails,$numberOfQuotes);
$fayl = $fails[$faisl[1]];

///////////////////////////////////////

?>