<?php

////////////////////////////////////////
// PRESENTACIONES ALEATORIAS

srand((float) microtime() * 10000000);

if ($tipoCombate != "umbral") {

$quote = array(

"<b>$nombre1</b> mira desafiante a <b>$nombre2</b>, se huele violencia en el aire...",
"¡Todos se preparan para el combate entre <b>$nombre1</b> y <b>$nombre2</b>!",
"<b>$nombre1</b> escupe en la cara a <b>$nombre2</b>. La pelea es inevitable.",
"En un acantilado precioso, el mar ser&aacute; testigo de la violenta batalla entre <b>$nombre2</b> y <b>$nombre1</b>.", 
"¡<b>$nombre1</b> se abalanza sobre <b>$nombre2</b>! ¡<b>$nombre2</b> aparta a <b>$nombre1</b> y se prepara para la lucha!",
"La presencia de <b>$nombre2</b> ofende a <b>$nombre1</b> sobremanera. ¡<b>$nombre1</b> se predispone a atacar!",
"¡El silencio de la noche se rompe para dar lugar al enfrentamiento entre <b>$nombre1</b> y <b>$nombre2</b>!"

);

} else {

$quote = array(

"Las tierras de la Umbra se estremecen por el enfrentamiento entre <b>$nombre1</b> y <b>$nombre2</b>.",
"¡La búsqueda espiritual de <b>$nombre1</b> choca con <b>$nombre2</b>!"

);



}
// Random quote is generated by array_rand and the variable is assigned to it
//The number in the parenthesis = number of quotes you have in total
$qtyText =  count($quote);

$echo = array_rand($quote,$qtyText);


////////////////////////////////////////
?>