<?php

////////////////////////////////////////
// DERROTAS ALEATORIAS

srand((float) microtime() * 10000000);
if ($tipoCombate != "umbral") {
$caexy = array(

"explota en una supernova de vísceras", 
"se desploma miserablemente",
"comienza a toser descontroladamente y un rato después, exhala su último aliento",
"cae al suelo para no levantarse jamás",
"muere dolorosamente",
"ha sufrido diversas hemorragias y no se puede mantener en pie",
"recibe un golpe mortal, empieza a expulsar sangre violentamente y ¡MUERE!",
"tiene los músculos demasiado entumecidos para continuar el combate",
"pierde el conocimiento por el dolor",
"acaba desangrándose en el suelo",
"queda fuera de combate",
"no consigue soportar las heridas y se desploma",
"revienta brutalmente, quedando sólo la parte inferior de su cuerpo"

);
} else {
$caexy = array(

"se desintegra en un tornado espiritual",
"fallece con violencia, perturbando a los espíritus cercanos",
"acaba desvaneciéndose sin dejar rastro"

);

}
$numberOfQuotes = count($caexy);
// Random quote is generated by array_rand and the variable is assigned to it
//The number in the parenthesis = number of quotes you have in total
$ceaxy = array_rand($caexy,$numberOfQuotes);
$kae = $caexy[$ceaxy[1]];

///////////////////////////////////////

?>